name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{matrix.os}}
    strategy: 
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        build_configuration: [Debug, Release]

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Boostrap Vcpkg
      - if: runner.os == 'Windows'
        run: ${{github.workspace}}\external\vcpkg\bootstrap-vcpkg.bat -disableMetrics
      - if: runner.os != 'Windows'
        run: ${{github.workspace}}/external/vcpkg/bootstrap-vcpkg.sh -disableMetrics

    #- if: runner.os == 'Windows'
    #  name: Install packaged dependencies
    #  run: ${{github.workspace}}\external\vcpkg\vcpkg.exe install spdlog --triplet x64-windows

    #- if: runner.os != 'Windows'
    #  name: Install packaged dependencies
    #  run: ${{github.workspace}}/external/vcpkg/vcpkg install spdlog --triplet x64-linux

    #- name: Configure CMake
    #  # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
    #  # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
    #  run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_configuration}} 
    #    -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/external/vcpkg/scripts/buildsystems/vcpkg.cmake

    #- name: Build
    #  # Build your program with the given configuration
    #  run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_configuration}}

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute tests defined by the CMake configuration.
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{matrix.build_configuration}}

